// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return macos;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAka37tyUU4eTlthw3b68HOiy5VQAW5XVM',
    appId: '1:615086013933:web:edf2ed13d2322b0bc1fbe4',
    messagingSenderId: '615086013933',
    projectId: 'flutter-firebase-210e5',
    authDomain: 'flutter-firebase-210e5.firebaseapp.com',
    storageBucket: 'flutter-firebase-210e5.appspot.com',
    measurementId: 'G-19DJGNMDLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrVccrRIBxzhQnTvsz1jK60oEn90f1oW0',
    appId: '1:615086013933:android:b483f151056155cbc1fbe4',
    messagingSenderId: '615086013933',
    projectId: 'flutter-firebase-210e5',
    storageBucket: 'flutter-firebase-210e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF_giKw_b_ltyubGVPTSTsx9TNyXrJUMc',
    appId: '1:615086013933:ios:36fac4a515edd7b0c1fbe4',
    messagingSenderId: '615086013933',
    projectId: 'flutter-firebase-210e5',
    storageBucket: 'flutter-firebase-210e5.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF_giKw_b_ltyubGVPTSTsx9TNyXrJUMc',
    appId: '1:615086013933:ios:3ad8923628d6ce03c1fbe4',
    messagingSenderId: '615086013933',
    projectId: 'flutter-firebase-210e5',
    storageBucket: 'flutter-firebase-210e5.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
